[package]
name = "servus"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = { version = "0", features = ["serde"] }
markdown = "0"
mime = "0"
mime_guess = "2"
serde = "1"
tera = "1"
toml = "0"
yaml-front-matter = "0"
